### ISSUE TITLE
Release for Modernizr 3.x branch?

### ISSUE THREAD

**Issue by al-the-x** [components/modernizr#6]
Version 2.8.3, the latest version released here, is dated July 2014, and there have been [a few v3.x releases in 2015](/Modernizr/Modernizr/tags). It's still very much a work in progress, but for the intrepid souls, at least a tagged release would be appreciated. Happy to open a PR for this, as well.

**Comment by mrohnstock** [comment]
I've made a commit for v3.5.0.
